### ISSUE TITLE
New icons for CC Search browser extension

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/fonts#105]
## Description
We need to add three new icons for the CC Search browser extension. The icons can be found in fontawesome and are:
1. Adjust
2. Bookmark regular
3. Bookmark solid

<img width="554" alt="Screen Shot 2020-07-01 at 12 56 52" src="https://user-images.githubusercontent.com/895819/86271264-96f1ad00-bb9a-11ea-8965-aa7b14b5ab3a.png">

The [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A135&viewport=-1282%2C-26%2C2.5631163120269775) is updated with this change.

**Comment by makkoncept** [comment]
@kgodey Can I work on this?

**Comment by zackkrida** [comment]
@makkoncept Yes, you can!
