### ISSUE TITLE
`.icon` Class mismatch with bulma/vocabulary

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/fonts#110]
## Description
`creativecommons/fonts` uses the class `.icon` on each icon. Bulma, and as a result vocabulary, uses the class `.icon` as a _wrapper_ for icons: https://bulma.io/documentation/elements/icon/

This means that we often end up with the following structure (taken _directly_ from cc search:)

```html
<div class="control has-icons-left margin-left-small">
  <input class="input is-medium"> 
  <span class="icon is-medium is-left"> <!-- ".icon" here is for bulma -->
    <i class="icon search is-size-5"></i> <!-- ".icon" here is for fonts -->
  </span>
</div>
``` 

This causes many styling issues, as bulma's classes are only meant for the _icon wrapper_ but get applied to the icon too. 

## Possible fixes

The only feasible fix I can see is that we change the `.icon` class in this library, but that would mean a lot of updating of our projects. The other approach would be to fork bulma and replace their usage of `.icon` with something like `.icon-wrapper`, but that doesn't seem wise.

**Comment by kgodey** [comment]
Assigned to @dhruvkb and @hugosolar for review and comment.

**Comment by dhruvkb** [comment]
Renaming the icon class might break a lot of things for a lot of projects in production and force a lot. Changing the selection from just the class `.icon` to element + class 
```
i.icon { ... }
```
could be a backwards-compatible way to do this imo.

**Comment by dhruvkb** [comment]
Since neither approach is backwards compatible and might cause a lot of trouble to the developers who are using Vocabulary icons in their projects, I think we can be to just use the CSS value `unset` on the few properties set by the Bulma `.icon` class on our `i.icon` selector (while we switch to a new icon class) to ensure a smoother transition. 

```scss
i.icon {
  display: unset;
  align-items: unset;
  justify-content: unset;
  height: unset;
  width: unset;
}
```

**Comment by zackkrida** [comment]
Fixed in vocabulary via https://github.com/creativecommons/vocabulary/pull/614
