### ISSUE TITLE
New icon: CC heart filled

### ISSUE THREAD

**Issue by fcoveram** [creativecommons/fonts#124]
## Description
We need to add a new icon: `CC heart filled`. The icon is available on the Design Library, icon page.

### Mockup
<img width="276" alt="Screen Shot 2020-08-14 at 09 27 33" src="https://user-images.githubusercontent.com/895819/90254219-68f5be80-de10-11ea-8850-7ac6f9b40de1.png">

**Comment by zackkrida** [comment]
@panchovm Maybe every time we add a new icon moving forward, we should automatically add the _filled_ version too. What do you think?

We often use the filled version for hover states, it seems.

**Comment by fcoveram** [comment]
I don't think that Fontawesome has filled versions for all icons we are using. Or at least under its free version.

**Comment by Aakash2408** [comment]
> ## Description
> We need to add a new icon: `CC heart filled`. The icon is available on the Design Library, icon page.
> 
> ### Mockup
> <img alt="Screen Shot 2020-08-14 at 09 27 33" width="276" src="https://user-images.githubusercontent.com/895819/90254219-68f5be80-de10-11ea-8850-7ac6f9b40de1.png">

   What is the path of design library,icon page.

**Comment by dhruvkb** [comment]
@Aakash2408 you can find them [in our Storybook](https://cc-fonts.netlify.app/?path=/docs/vocabulary-icons--page).

**Comment by Aakash2408** [comment]
@panchovm  ok so how we need it like can we use any editor and make it in the form of image,taking reference from the old icon.

**Comment by dhruvkb** [comment]
@panchovm please attach the SVG for this icon as a 496x496 image on a 512x512 canvas to this issue if possible.

**Comment by fcoveram** [comment]
Yes! Sorry @dhruvkb, I forgot it 😅

[cc-heart-filled SVG.zip](https://github.com/creativecommons/fonts/files/5097153/cc-heart-filled.SVG.zip)

**Comment by dhruvkb** [comment]
@Aakash2408 extremely sorry, but we're due for a release today so I have to take this.

**Comment by Aakash2408** [comment]
> @Aakash2408 extremely sorry, but we're due for a release today so I have to take this.

 ok no problem I was just gonna ask you where to make changes.

**Comment by Aakash2408** [comment]
ok, I get it was needed to be replaced with cc-heart.
