### ISSUE TITLE
Replace JS stories with MDX Docs

### ISSUE THREAD

**Issue by megha070** [creativecommons/fonts#25]
**Description**
Replace stories written in `.stories.js` files with MDX docs written in `.stories.mdx` format.

**Problems solved**
MDX presents a better way of combining code examples with long form documentation. It also enables the use of DocsPage components such as `Typeset` and `IconGallery`.

**Want to take up?**

[Yes|No]
Yes

**Comment by dhruvkb** [comment]
@megha070 do you want to work on this? Set the answer in the **Want to take up?** section in the issue description.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
I would also like to work on this

**Comment by kushaggarwal** [comment]
I suppose that @megha070 have linked the changes to the issue of replacement with mdx stories for all components 
@dhruvkb can you please help as if any of it is left on which I can continue working  
Thanks

**Comment by dhruvkb** [comment]
@kushaggarwal see #31.
