### ISSUE TITLE
Update usage and contribution guidelines

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/fonts#29]
**Description**
Vocabulary has started to move usage and contribution guidelines outside of the `README.md` and `INSTRUCTIONS.md` file to Storybook docs as the single source of truth. See creativecommons/vocabulary#214 and creativecommons/vocabulary#272. A similar approach should be taken here.

**Problems solved**
This is to be done for consistency and, more importantly, because it enables us to have documentation on the landing page.

**Additional context**
This issue supersedes #21 and #23.

**Checklist**
- [ ] Usage guidelines
- [ ] Contribution guidelines

**Comment by megha070** [comment]
@dhruvkb I would like to take this up.

**Comment by dhruvkb** [comment]
One at a time please. You are already working on #28.

**Comment by megha070** [comment]
@dhruvkb made necessary changes to #28. Please review!
