### ISSUE TITLE
Develop a font preview table

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/fonts#3]
**Description**
Develop a table, like the one shown below, to see most characters of the font in one go. This would allow us to quickly see most, though not all, of the characters, giving glanceable information about the aesthetics of the font.

**Additional context**
This table was taken from the CC Accidenz Commons introductory blog post.
![image](https://user-images.githubusercontent.com/16580576/75613841-0c4f6180-5b58-11ea-9797-fac767ab4f56.png)

**Comment by kushaggarwal** [comment]
Hello,
I would like to go for this issue

**Comment by kushaggarwal** [comment]
In what format does the table need to be aligned for the same @dhruvkb can you please help

**Comment by dhruvkb** [comment]
I can't think of any good alignment to arrange these characters. See if you can come up with something.
- 26 characters from `A - Z`
- 26 characters from `a -z
- 10 numbers from `0 - 9`
- the following symbols
```
+ - * / %
@ # $
< > ( ) { } [ ] 
& , . ? ! 
```

These could also be split into separate stories, making the process much simpler.

**Comment by kushaggarwal** [comment]
Okay will start working with the same
Thank you

**Comment by kushaggarwal** [comment]
As you have described in the above mentioned format I have aligned the elements in the similar form kind of giving the look and feel of a keyboard with one story as the name of the font with subsection each describing the types of characters like uppercase, lowercase.
Below is a screenshot for reference please guide for the same .
Thankyou
![Screenshot 2020-03-02 at 2 16 43 PM](https://user-images.githubusercontent.com/44523552/75660742-20977980-5c92-11ea-92e4-a7b073804647.png)

**Comment by kushaggarwal** [comment]
Also I have given a effect upon hovering as in below image to further elevate the look and feel of it, please advice for the same too
![Screenshot 2020-03-02 at 2 31 41 PM](https://user-images.githubusercontent.com/44523552/75661039-94d21d00-5c92-11ea-929d-19f2f4400bd8.png)

**Comment by kushaggarwal** [comment]
@dhruvkb can you please guide as if above design is fine  and also which all font styles are we targeting for the above mentioned issue

**Comment by dhruvkb** [comment]
@kushaggarwal It looks good, and the hover effect is a nice touch, but I would prefer
- left aligned, not center
- slight grey background on hover instead of completely inverted
- more uniform distribution of characters, instead of 10-8-6-2
- mobile responsive, _if feasible_

**Comment by kushaggarwal** [comment]
Okay @dhruvkb will start working keeping above points in mind 
Please can you share what other fonts style we are targeting to integrate
Thank You

**Comment by kushaggarwal** [comment]
Hello @dhruvkb  please see for the attached screenshot regarding the changes and improvements as recommended by you for all three types Uppercase, Lowercase and Numbers 
![Screenshot 2020-03-04 at 12 14 06 PM](https://user-images.githubusercontent.com/44523552/75852390-df2dd800-5e11-11ea-8276-28c658889fcd.png)
![Screenshot 2020-03-04 at 12 14 01 PM](https://user-images.githubusercontent.com/44523552/75852392-e05f0500-5e11-11ea-9b1d-3e5b0db34d39.png)
![Screenshot 2020-03-04 at 12 13 56 PM](https://user-images.githubusercontent.com/44523552/75852397-e0f79b80-5e11-11ea-9dee-de12d9764c87.png)

**Comment by kushaggarwal** [comment]
Hello @dhruvkb please find  the below attached screenshot regarding the improvement and changes as recommended by you for the three types i.e Uppercase, Lowercase and Numbers
Thank you
![Screenshot 2020-03-04 at 12 20 39 PM](https://user-images.githubusercontent.com/44523552/75852758-b35f2200-5e12-11ea-9512-d171a1c5a4b7.png)
![Screenshot 2020-03-04 at 12 20 42 PM](https://user-images.githubusercontent.com/44523552/75852759-b4904f00-5e12-11ea-8db5-08773fb8b474.png)
![Screenshot 2020-03-04 at 12 20 45 PM](https://user-images.githubusercontent.com/44523552/75852760-b5c17c00-5e12-11ea-911a-763823379316.png)

**Comment by dhruvkb** [comment]
Looks good, you should open a draft PR so that we can review it as you work on it. It's generally good advice to have a draft PR open as soon as you start working on any issue.

**Comment by kushaggarwal** [comment]
Okay will do so thanks 
Also @dhruvkb can you please help me with what other are font styles are we targeting for this particular improvement so that I can start with that too
Thank You

**Comment by dhruvkb** [comment]
We are not targeting Times New Roman, we need this kind of preview in the already existing CC Accidenz Commons story for now.

**Comment by kushaggarwal** [comment]
Okay will update the component for the same

**Comment by kushaggarwal** [comment]
Hello @dhruvkb have updated the font style to accidez commons and commited the changes too 
Shall I start for the other font styles too in the same request or should I turn this pull request to ready for review from draft 
Please guide 
Thank you
