### ISSUE TITLE
Add Snapshot Testing

### ISSUE THREAD

**Issue by jahnvigupta** [creativecommons/fonts#30]
**Description**

The goal is to add test visual tests for all the components to ensure that the designs are not changed with change in code.
**Problems solved**

Tests make it easy to identify breaking changes and fix them as and when they occur.

**Alternatives**

**Additional context**

**Want to take up?**

Yes

**Comment by kushaggarwal** [comment]
If available I would like to attend to this @dhruvkb

**Comment by silvinabt87** [comment]
@jahnvigupta @dhruvkb @kushaggarwal I'd like to help here too. We could divide components between us.

**Comment by dhruvkb** [comment]
@jahnvigupta given your experience in doing so, I'd recommend you set up the infrastructure. @silvinabt87 and @kushaggarwal can split the components between themselves.

Please refer to creativecommons/vocabulary for reference on the implementation such as directory structure and `npm` scripts.

**Comment by silvinabt87** [comment]
@dhruvkb @jahnvigupta I'm reading the previous tests and about Snapshots to work on this. I'm confused as regards what actually needs to be tested on the Fonts repository. To which components are we referring to? I assumed it was the Vocabulary components, but that's a different repo. Can you help me on this, please?

**Comment by jahnvigupta** [comment]
You need to create tests for uppercaseLetters, lowercaseLetters, numbers, pangrams, icons page. Basically, we are taking snap of the component implemented in vocabulary and using that to ensure that there are no changes in component design when the code changes.

**Comment by kushaggarwal** [comment]
@jahnvigupta I suppose it will work in the same manner as you did in vocabulary ?

**Comment by jahnvigupta** [comment]
> @jahnvigupta I suppose it will work in the same manner as you did in vocabulary ?

yes @kushaggarwal

**Comment by kushaggarwal** [comment]
Okay thanks 
@silvinabt87 which all components are you planning to take up so, that we can work together on this issue

**Comment by silvinabt87** [comment]
@kushaggarwal if it's ok with you, I'd like to try icons to begin with, which I think I understand more clearly. Then I can move on to any other component

**Comment by jahnvigupta** [comment]
@silvinabt87 I just realised that Icons Page has no story so you won't be able to create test for that. I am sorry. Please start with some other component.

**Comment by kushaggarwal** [comment]
@silvinabt87 in such a case I think both of us can take up the font components for the purpose of snapshot testing

**Comment by silvinabt87** [comment]
@kushaggarwal cool! I can do uppercase and lowercase if it's OK with you. Let me know!

**Comment by kushaggarwal** [comment]
As decided lets pick up one font components each and then start testing for the same

**Comment by silvinabt87** [comment]
@dhruvkb I did a PR with some preliminary work done to solve the issue. I couldn't find where the error is and I need some guidance, if possible. I seem to have something missing, maybe in the dependencies, and no test is found when I run ```npm run test```. The actual test may not be correct but before improving that file, I'd like to have the previous step solved.

**Comment by jahnvigupta** [comment]
@silvinabt87 you need to run this command "npm run test:integration".
This will help you:
https://storybook.js.org/docs/testing/automated-visual-testing/

**Comment by kushaggarwal** [comment]
@dhruvkb can you please 
I have set up the snapshot testing for the roboto condensed font component but when I am trying to set up a common helper template it gives an error upon importing the function from there 
the screenshot for the same is as follows
![Screenshot 2020-04-03 at 11 44 54 PM](https://user-images.githubusercontent.com/44523552/78392195-70f15680-7605-11ea-88d7-0c59dcc1b379.png)

**Comment by jahnvigupta** [comment]
@kushaggarwal Can you share your test code. I also faced this issue and the problem was in test code.

**Comment by kushaggarwal** [comment]
Okay @jahnvigupta 
![Screenshot 2020-04-04 at 10 19 28 AM](https://user-images.githubusercontent.com/44523552/78418863-d07b5080-765d-11ea-87c7-19c8bc81e3ee.png)
here is the screenshot my test code

**Comment by jahnvigupta** [comment]
@kushaggarwal  Try this
import { setViewport, goTo, pause } from './helpers'

describe('Roboto Condensed Story', () => {
  it('Default', async () => {
    await setViewport(page)
    await goTo(page, 'roboto-condensed--uppercase-letters')
    await pause(1000)
    const image = await page.screenshot()

    expect(image).toMatchImageSnapshot()
  })
})

**Comment by kushaggarwal** [comment]
I tried with the above code too but the same error still persists

**Comment by jahnvigupta** [comment]
@kushaggarwal 
Run npm run storybook in one terminal
and test command in another

**Comment by kushaggarwal** [comment]
@jahnvigupta 
Still getting the same error

**Comment by jahnvigupta** [comment]
@kushaggarwal 
I ran this command 
npm i --save-dev jest-image-snapshot
and it worked

**Comment by jahnvigupta** [comment]
![Screenshot from 2020-04-04 15-31-09](https://user-images.githubusercontent.com/43217070/78424627-79d93b00-768c-11ea-9827-a26979853051.png)

**Comment by kushaggarwal** [comment]
@jahnvigupta 
Can you please share the structure for your snapshot test 
Thanks

**Comment by jahnvigupta** [comment]
I ran your code only.

**Comment by kushaggarwal** [comment]
Okay 
@dhruvkb can you please help with the above issue

**Comment by jahnvigupta** [comment]
@kushaggarwal update your local repo and run your test.

**Comment by silvinabt87** [comment]
@dhruvkb I tried changing some files but still there is an error (shown in #56 ) that I can't seem to solve. If possible, I'd need some assistance.

**Comment by dhruvkb** [comment]
I think there's a confusion on running the tests. You need to run the snapshots test using Docker. That's the only way to get OS-independent, browser-independent, version-independent snapshots. See [instructions](https://cc-vocabulary.netlify.com/?path=/docs/vocabulary-contribution--page#testing) from the Vocabulary storybook.

**Comment by dhruvkb** [comment]
I've added a sample snapshot test in `tests/snapshot/`. The commands for running the tests are 
```
$ npm run test:unit
```
and
```
$ ./docker/puppeteer/run.sh
[in the container]$ npm run test:snapshot
```
