### ISSUE TITLE
Add bold (700) weight for Roboto Condensed

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/fonts#31]
**Description**
Vocabulary uses Roboto Condensed weight 700. It's not added at present but it should be. The goal is to add the weight and all associated documentation.

**Additional context**
Weight 400 was added in #5.

**Comment by kushaggarwal** [comment]
I would like to take this up @dhruvkb 
Thank you

**Comment by kushaggarwal** [comment]
For the updation of the weights I suppose changes need to be made in the `src/stories/roboto_condensed.stories.mdx`
Please advise @dhruvkb

**Comment by kushaggarwal** [comment]
@dhruvkb can you please help

**Comment by Tanuj22** [comment]
@kushaggarwal have a look as to how it was added for Source Sans Pro. If you need any further help let me know

**Comment by kushaggarwal** [comment]
Okay @Tanuj22 
Thanks

**Comment by kushaggarwal** [comment]
It seems that the bold file woff,woff2 for roboto condensed isnt available in the current repository
So, @dhruvkb can you please advice as if should how should I proceed further

**Comment by kushaggarwal** [comment]
@dhruvkb can you please help

**Comment by dhruvkb** [comment]
I'm really sorry I hadn't checked in. Can you find the WOFF or WOFF2 files for Roboto Condensed from their officail repositories?

**Comment by kushaggarwal** [comment]
Yes sure @dhruvkb 
Will start working for the same

**Comment by kushaggarwal** [comment]
Hello @dhruvkb I have linked a pull request for Roboto Bold Addition
I noticed that in the current Source-Sans Pro there seems to be Semi Bold too which hasnt been added 
So, shall I make a pull request for that too in roboto as well as in accidez common  
Please help

**Comment by dhruvkb** [comment]
@kushaggarwal I'm pretty sure Source Sans Pro has a semibold version with weight 600. Is your branch up to date? Here is a [list of all fonts](https://github.com/creativecommons/fonts/tree/master/src/fonts).

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
I have updated the current repository of mine and updated the PR too

**Comment by kushaggarwal** [comment]
> @kushaggarwal I'm pretty sure Source Sans Pro has a semibold version with weight 600. Is your branch up to date? Here is a [list of all fonts](https://github.com/creativecommons/fonts/tree/master/src/fonts).

I think I wasnt able to make the point clear I wanted to ask that should I add the semi bold font for the roboto-condesed font story as it is not present till now 
@dhruvkb Please help

**Comment by dhruvkb** [comment]
No @kushaggarwal we only need Roboto Condensed in 400 and 700 versions.

**Comment by kushaggarwal** [comment]
@dhruvkb can you please help as if the addtion of bold or semi bold needs to be done for accidez common font too
Thanks
