### ISSUE TITLE
Write Unit Tests for components in fonts

### ISSUE THREAD

**Issue by megha070** [creativecommons/fonts#36]
**Description**
The goal is to add unit testing to the repository for all the components

**Problems solved**
Tests make it easy to identify breaking changes and fix them as and when they occur.

**Alternatives**

**Additional context**

**Want to take up?**

[Yes|No]
Yes

**Comment by kushaggarwal** [comment]
Hello 
I would also like to contribute to this issue

**Comment by kushaggarwal** [comment]
@dhruvkb please advice as I suppose the unit test here needs to be only implemented for the icons and font-face in styles files
As others are importing the same for implementation

**Comment by dhruvkb** [comment]
Cool, @kushaggarwal you take the mixins in the icons and @megha070 you take the mixins in fonts.

**Comment by kushaggarwal** [comment]
Okay thank you @dhruvkb will start working on it
