### ISSUE TITLE
Deploy .scss files

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/fonts#37]
The bundled .css file includes everything: Accidenz Commons, Roboto Condensed, Source Sans Pro and the Icons. That's a lot of KBs for a website to load, specially if a website needs only one or two of those things (eg: a website that needs only the icons, or the icons and Roboto Condensed font).

We should deploy the .scss files separately to allow users to import modules individually

**Comment by dhruvkb** [comment]
Since SCSS files will be compiled in the parent app and break because of an absence of the fonts, deploying independent CSS files would be a better option.
