### ISSUE TITLE
Add Roboto and Souce Sans Pro

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/fonts#4]
**Description**
Apart from CC Accidenz Commons, the CC sites use 'Roboto' and 'Source Sans Pro' in their UIs. Citing benefits listed in https://github.com/creativecommons/fonts/issues/1#issuecomment-548986367, it would be wise to include those fonts here as well.

**Problems solved**
https://github.com/creativecommons/fonts/issues/1#issuecomment-548986367

**Alternatives**
We are currently importing those fonts into Vocabulary from Google Fonts, which works perfectly fine although there is scope for improvement.

**Comment by Tanuj22** [comment]
@dhruvkb Can I work on this?

**Comment by dhruvkb** [comment]
@Tanuj22 please do.

**Comment by Tanuj22** [comment]
@dhruvkb This is the stylesheet in Vocabulary https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700|Roboto+Condensed. Should I define fonts for every part like cyrillic, greek etc. ?

**Comment by megha070** [comment]
@dhruvkb if no one is working on this, Shall I take this up?

**Comment by Tanuj22** [comment]
@megha070 I am already working on this issue and have a PR open. I will make the requested changes in the PR soon. Please find another issue to work upon.

**Comment by megha070** [comment]
Alright!
