### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/fonts#52]
**Description**
GitHub Actions is providing a feasible alternative to CircleCI for running tests on branches and PRs. It has been implemented in Vocabulary creativecommons/vocabulary#245 and along similar lines must also be implemented in this repository.

**Problems solved**
GitHub Actions has similar features, better integration and higher usage limits as compared to CircleCI. Switching would be the best option.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb I would like to take this up

**Comment by kushaggarwal** [comment]
Hello @dhruvkb I went through the GitHub actions in vocabulary repository for reference 
So, can you please help as if the same steps and jobs need to be present for the fonts repository 
Thanks

**Comment by dhruvkb** [comment]
Check the current CircleCI config in Fonts for the jobs that you need to setup here.

**Comment by kushaggarwal** [comment]
Okay @dhruvkb will follow accordingly
