### ISSUE TITLE
Run Visual Regression tests inside CI

### ISSUE THREAD

**Issue by megha070** [creativecommons/fonts#65]
**Description**

With visual regression tests running stably inside Docker, we can consider merging them into the CI pipeline with GitHub Actions.

**Problems solved**

Visual regression tests bring a lot of the errors happening in the course of the development to light, such as a change in element dimensions, textual content and even subtle changes in colors

**Alternatives**

**Additional context**

**Want to take up?**

[Yes|No]
yes

**Comment by dhruvkb** [comment]
Blocking till we iron out the kinks of running visual regression tests in Vocabulary.

**Comment by kgodey** [comment]
We're not doing visual regression tests right now, closing.
