### ISSUE TITLE
Caching dependencies to speed up CI workflow

### ISSUE THREAD

**Issue by megha070** [creativecommons/fonts#74]
**Description**
Using the cache-hit output, subsequent steps (such as install or build) can be skipped when a cache hit occurs on the key.

**Reproduction**

**Expected behavior**
This should speed up the CI workflow

**Screenshots**

**Conditions:**

**Additional context**

**Want to take up?**

[Yes|No]
Yes

**Comment by kgodey** [comment]
We've disabled visual regression testing, closing this issue.
