### ISSUE TITLE
Add more relevant fonts

### ISSUE THREAD

**Issue by Dishebh** [creativecommons/fonts#78]
**Description**

I would like to add more relevant fonts to the project. @dhruvkb please suggest if I should go for it? I'm new to the project and would like to contribute.

**Want to take up?**

Yes

**Comment by dhruvkb** [comment]
@Dishebh this repo only contains fonts that are currently in use in at least one CC project. Before we decide to add more fonts, we should discuss which fonts and why.

**Comment by Dishebh** [comment]
@dhruvkb makes sense, thanks for clarifying. Since I'm new to the project and would like to participate as a technical writer under CC, I was naturally looking for some beginner-friendly issues to get started with. As to which font to add and why? I'm not really sure about that and so that's why asked you. Kindly let me know if you feel there's a need to add an extra font, and I would be glad to take up the issue. Feel free to close the issue if you feel there's no need for it now. Thanks!

**Comment by dhruvkb** [comment]
@Dishebh I appreciate the initiative. Let's ask @panchovm which monospaced font we're going to be using in the CC OS redesign with and we can add that to our collection.

**Comment by fcoveram** [comment]
For now, the fonts selected solve all content needs. We are using `JetBrains Mono` for code, in two styles: code big, code normal.

**Comment by Dishebh** [comment]
@panchovm @dhruvkb So I have to add `JetBrains Mono` font to the repo, right?

**Comment by fcoveram** [comment]
Yes. Exactly
