### ISSUE TITLE
write snapshot test for jetbrains mono typeface

### ISSUE THREAD

**Issue by Dishebh** [creativecommons/fonts#81]
**Description**

write snapshot test for jetbrains mono typeface

**Want to take up?**

[Yes]

**Comment by Dishebh** [comment]
@dhruvkb can I work on this? Also, it seems I do not have the permission rights to add snapshot image to the __image_snapshots__ directory.

**Comment by dhruvkb** [comment]
Actually snapshot tests are proving to be highly fragile and we have turned them off in Vocabulary. Until we can either find a way to make them super reliable, we cannot move forward with it in production.

**Comment by kgodey** [comment]
Closing because we disabled snapshot tests.
