### ISSUE TITLE
Move CC license icons to the right code points

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/fonts#92]
## Description
Since CC licenses have been included in the Unicode Standard, we can expect more and more fonts to start supporting the license icons in the future. Having the icons at the right code-points would mean that they can then be easily copied and pasted into a different document using a supported font while working as expected.

## Additional context
The [blog post by Eric Steuer](https://creativecommons.org/2020/03/18/the-unicode-standard-now-includes-cc-license-symbols/) that prompted this issue contains more information and the code-points for the license icons.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by Tanuj22** [comment]
@dhruvkb I would like to work on this. From what I understood I need to edit the code-points but I am a bit confused which are the code points?
![licnesing-options-unicode-13 0-symbols-1024x726](https://user-images.githubusercontent.com/42486853/84423036-85705180-ac3b-11ea-8544-273842096432.jpg)
Are these it?

**Comment by Dishebh** [comment]
@dhruvkb can I work on this?

**Comment by dhruvkb** [comment]
Yes, each font is basically a mapping of a unicode code-point (the blue box in your image) to a glyph (the symbols you actually see on the screen). Currently all the CC icons are assigned to 4-digit code-points instead of these 5-digit ones.
